sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t brailor/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run brailor/react-test npm test

after_success:
  - docker build -t brailor/multi-frontend ./frontend
  - docker build -t brailor/multi-nginx ./nginx
  - docker build -t brailor/multi-server ./server
  - docker build -t brailor/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push brailor/multi-frontend
  - docker push brailor/multi-nginx
  - docker push brailor/multi-server
  - docker push brailor/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-376518002133
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"